### PR TITLE
add ch.3 kidscore_momiq model and modified references.bib

### PR DESCRIPTION
**Pull request by jarnefeltoliver**
I also added a directory of add_scripts like we discussed

### CODE REVIEW

**Comment by MansMeg** [comment]
Great! Two comments. First, we do not want posterior_database/add_scripts/.Rhistory in the database and likewise (for now) we do not want the add scripts in the database. They can be good for you to store locally, but in the database we only want the info generated.

**Comment by MansMeg** [comment]
Great! The data, thats already in the database right?

**Comment by jarnefeltoliver** [comment]
Yes, they had different author and date fields.

________________________________
Lähettäjä: Måns Magnusson <notifications@github.com>
Lähetetty: 13. tammikuuta 2020 14:33:18
Vastaanottaja: MansMeg/posteriordb
Kopio: Järnefelt Oliver; Author
Aihe: Re: [MansMeg/posteriordb] add ch.3 kidscore_momiq model and modified references.bib (#126)


Great! The data, thats already in the database right?

**Comment by MansMeg** [comment]
Great!

**Pull request merged**
