### PR TITLE
WIP: Add test for checking that generated readme is up-to-date

### LINKED ISSUE #65: Add CI check for generated README
It would be good to make sure in CI that the generated README is up-to-date. So essentially test that
```R
read.file("README.md") == generate_from_Rmd("README.Rmd")
```
where `generate_from_Rmd` would be a function that generates markdown file from R-markdown file (I guess a function like this might exist already but I don't know the real name)

### PR DESCRIPTION
**Pull request by eerolinna**
Fixes #65 

This test sort of works right now, but not completely yet.

- The generation settings on travis seem to be slightly different from what was used to generate the current README (see later comments in this thread)
- The code outputs contain absolute paths like
  ```R
  dfp <- data_file_path(po)
  dfp
  ## [1] "/var/folders/9h/yf354vb917z6gr6mz7bfb1d40000gn/T//RtmptE97ZB/posteriordb_cache/data/data/eight_schools.json"
  ```
  These paths will be different when running on CI, causing the test to fail
- The test might not work on Windows as it uses unix-style paths

### CODE REVIEW

**Comment by eerolinna** [comment]
Looks like `readLines("../../../README.md")` doesn't work on travis (it did work locally)

**Comment by eerolinna** [comment]
Now the logic of the test works and the remaining test failures are from actual differences between current `README.md` and what travis generates from `README.Rmd`

> ── 3. Failure: Check that the generated README is up-to-date (@test-readme.R#8) 
  `current_readme` not equal to `generated_readme`.
  28/367 mismatches
  x[148]: "    ##   name   model_name gold_standard_n… data_name added_by added_date
  x[148]:  keywords"    
  y[148]: "    ##   name     model_name   gold_standard_na… data_name added_by added
  y[148]: _date keywords"

etc, see https://travis-ci.org/MansMeg/posteriordb/jobs/614618733 for more

I guess there is some truncation length variable that is different between travis and what was used to generate the current README that should not be too hard to fix.

The issue with machine-specific paths like
```R
dfp <- data_file_path(po)
dfp
## [1] "/var/folders/9h/yf354vb917z6gr6mz7bfb1d40000gn/T//RtmptE97ZB/posteriordb_cache/data/data/eight_schools.json"
```
still remains though. @MansMeg do you have any ideas on how to tackle it?

**Comment by eerolinna** [comment]
The current failure is due to for example `gold_standard_n…` and `gold_standard_na…` not matching, which is more about having different truncation thresholds than whitespace. I don't think there should be any whitespace differences*? (let me know if you saw something)

A problematic situation is
```R
dfp <- data_file_path(po)
dfp
```
Where on one computer the result might be
```R
## [1] "/var/folders/9h/yf354vb917z6gr6mz7bfb1d40000gn/T//RtmptE97ZB/posteriordb_cache/data/data/eight_schools.json"
```
and on other computer
```R
## [1] /home/eero/...
```

The truncation thresholds should be pretty easy to solve but this one I don't know what to do about.

[*] The newline in
```
x[148]: " ## name model_name gold_standard_n… data_name added_by added_date
x[148]: keywords"
y[148]: " ## name model_name gold_standard_na… data_name added_by added
y[148]: _date keywords"
```
is in different place which could be considered a whitespace difference, but ultimately it was caused by different truncation length.

**Comment by MansMeg** [comment]
So:
1) I suggest you remove all lines with search path. That would solve the first issue.
2) I guess we can try to avoid the truncation somehow? Can that be specified as a parameter?

**Comment by eerolinna** [comment]
I don't think I'm going to work on this in a while. Feel free to pick this up if you want to.

**Comment by MansMeg** [comment]
This is not prioritized for me right now so Ill wait.

**Comment by MansMeg** [comment]
I have now included tests for the README and CONTRIBUTING markdown files. Not exactly the same, but the same purpose.

**Pull request closed without merging**
