### PR TITLE
Remove duplicate contents from syn_ zip dataset files

### PR DESCRIPTION
**Pull request by eerolinna**
These `syn_blr` zip files had two files inside them

For example `syn_blrD5N500C07.json.zip` used to have `syn_blrD5N500C07.json` and `syn_blrD5n500C07.json.zip` (with lowercase n). Now it only has `syn_blrD5N500C07.json` (which matches the zipfile name when `.zip` is omitted).

For one of these zipfiles I checked that the two jsons inside them are identical. I assume the same holds for the rest.

### CODE REVIEW

**Comment by eerolinna** [comment]
Could this be merged now? The failing CI is not from these commits but instead from master

**Comment by eerolinna** [comment]
I rebased the CI fix from #51 to here also so we can see that there's no issues. This can be merged after #51 has been merged

**Comment by eerolinna** [comment]
This PR is now over 1 month old. If you don't have the time to look over PRs can you give me rights to merge them myself? I would still open PRs and leave them open for some time before merging to allow for comments, but having to wait a month seems excessive

**Comment by MansMeg** [comment]
Sorry. It is my todo, missed to follow up this PR.

**Pull request merged**
