### PR TITLE
Adapt to new posterior database structure

### LINKED ISSUE #8: Adding models of different frameworks needs duplication in many posterior files
Let's say I want to add a PyMC version of the [logistic model](https://github.com/MansMeg/posterior_database/blob/master/content/models/logistic/logistic.stan). 

Then I need to modify these posterior files 
- wells_centered_educ4_interact|logistic.json 
- wells_centered_educ4|logistic.json
- wells_centered|logistic.json
- wells_noncentered_log|logistic.json
- wells_noncentered|logistic.json

and change 
```json
"model": {
    "stan": "content/models/logistic/logistic.stan"
  },
```
to
```json
"model": {
    "stan": "content/models/logistic/logistic.stan",
    "pymc": "path/to/model.py"
  },
```
in all of them.

Can we make it so that this change would need to be made only in one file?

### PR DESCRIPTION
**Pull request by eerolinna**
This pull request changes to new posterior database structure and adapts rpackage to the new structure.

Fixes #8

### CODE REVIEW

**Comment by eerolinna** [comment]
The problem with this solution is that we no longer have access to the data names and model names from `po`. One way to fix this would be to add 

```R
po$data_name <- po$data
po$model_name <- po$data
```
to `posterior` in `posterior.R`

This is maybe not the best solution still though

**Comment by eerolinna** [comment]
Another way would be not to overwrite `po$model` and `po$data` but instead make new fields like `po$model_info` and `po$data_info`

A third way would be to not attach the info file contents to `po` but load them on-demand. Then for example in `model_code_file_path`

https://github.com/MansMeg/posterior_database/blob/96dcb71330f376edecf9b7f8613c067d0d58cb85/rpackage/R/model_code.R#L12

would become something like 

```R
model_info <- load_model_info(x$model)
mcfp <- file.path(x$pdb$path,  model_info[[framework]]) 
```

**Comment by eerolinna** [comment]
Now this PR doesn't overwrite anything.

The slots in the posterior object are now
- `model_name`: from posterior json file
- `data_name`: from posterior json file
-  `model_info`: contents of model info file
- `data_info`: contents of data info file

**Comment by eerolinna** [comment]
This should include everything that is needed now. I think you haven't added the contributor etc slots yet so I couldn't include them here. Would be great if you can first merge this and then add the new slots

**Comment by eerolinna** [comment]
I found a problem in master branch that was causing tests to fail, some dataset zip files had json files inside them with wrong filename (lowercase n instead of capital N) that caused `stan_data(po)` to not find the data file, I corrected that here also.

**Comment by MansMeg** [comment]
Great! I had problem finding that problem yesterday.

**Pull request merged**
