### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by ahartikainen**
Move testing under Github Actions.

### CODE REVIEW

**Comment by ahartikainen** [comment]
I will clean the commits after we fix the R tests.

There is some error with github access which causes some tests to fail.

**Comment by ahartikainen** [comment]
I think this starts to look good.

Is there a command like `pip freeze` to see all the installed packages and their versions? I have find this very useful when things break (easy to find versions which don't fail and then compare against failing ones). And usually just printing them out is enough.

**Comment by MansMeg** [comment]
Sure. `sessionInfo()` is usually sufficient. Ill give it a try.

**Comment by ahartikainen** [comment]
I somehow feel that the cache part is not currently correct (I mean my "fix" is not correct, or does it need some hash)

**Pull request merged**
