### PR TITLE
Add python library

### PR DESCRIPTION
**Pull request by eerolinna**
This adds a python library for interfacing with the posterior database

View the code examples here: https://github.com/eerolinna/posterior_database/blob/python/python/README.md

This is a draft PR because I will probably rewrite commit history to be cleaner, but this can be reviewed now.

### CODE REVIEW

**Comment by MansMeg** [comment]
So are you done? Should I review it?

**Comment by eerolinna** [comment]
You should at least take a look at https://github.com/eerolinna/posterior_database/blob/python/python/README.md Reviewing the other parts would be good too

I might add more documentation etc but I don't plan on changing the core code

**Comment by MansMeg** [comment]
Great! I looked at it and it looks good. The question is how we can test both packages using Travis efficiently though. Or should we have different CI for Python?

**Comment by eerolinna** [comment]
I have a `travis.yml` at https://github.com/eerolinna/posterior_database/blob/python/.travis.yml that tests both python and R

Currently I think it runs the R tests twice. You can see at https://travis-ci.org/MansMeg/posteriordb/builds/574245486?utm_source=github_status&utm_medium=notification that there's two jobs
- Python: 3.6 R: release
- Python: 3.7 R: release

We could split the R into separate jobs so we could have
- Python: 3.6
- Python: 3.7
- R: release
- R: devel (which is currently inactive)

This can be done by including the R jobs under `matrix`

I think
```yml

matrix:
  include:
    - language: python
      python: "3.6"
      before_install: cd python
      install: pip install tox-travis
      script: tox
    - language: python
      python: "3.7"
      before_install: cd python
      install: pip install tox-travis
      script: tox
    - language: R
      R: release
      before_install: cd rpackage
      warnings_are_errors: True
      etc: ...
    - language: R
      R: devel
      before_install: cd rpackage
      warnings_are_errors: True
      etc: ...
```

Should do the job. It's a bit more verbose because you essentially have to unroll the build matrix manually, but I think it should be OK

**Comment by eerolinna** [comment]
Do you think that if you had to make some small change to the python code you could do it? If yes then I think we are almost ready to merge (I could try to tidy up the commit history a bit). If not then it might be worth it to add some extra documentation etc before merging.

**Comment by eerolinna** [comment]
This is ready for merge now

**Comment by eerolinna** [comment]
I did some final cleanups, feel free to merge

**Comment by MansMeg** [comment]
Great job Eero!

**Comment by MansMeg** [comment]
Now its not running the R tests. Will you fix or should I?

**Pull request merged**
