### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by eerolinna**

### CODE REVIEW

**Comment by eerolinna** [comment]
Oops my editor removed trailing whitespace that is autogenerated by R and thus should be kept, I will add it back in a second

**Comment by eerolinna** [comment]
Ok now this is ready to be merged.

**Comment by eerolinna** [comment]
The CI failure is due to github rate limiting

> GitHub API error (403): 403 Forbidden
  API rate limit exceeded for 35.202.145.110. (But here's the good news: Authenticated requests get a   higher rate limit. Check out the documentation for more details.)

**Comment by MansMeg** [comment]
So the package fails. The reason is that apparently the Github PAT is not used in the PR so then the number of calls to the GitHub APi fails. Do you know how this can be fixed for PR?

**Comment by eerolinna** [comment]
I restarted the travis build which solved it for this PR. We might run into this again in the future, especially when the posterior database is bigger. It is possible to add `GITHUB_PAT` as a hidden environment variable to travis, however it seems that then PRs won't be able to use it, which partly defeats the point of doing it https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

I guess we should wait and see if this problem occurs frequently and then figure something out if needed.

**Comment by MansMeg** [comment]
Indeed. I can also reduce the github tests in the R build.

**Comment by eerolinna** [comment]
Yeah that could be an option. We could have a small posterior database for testing that the github logic works as intended and then run the full tests only on a local database.

**Comment by MansMeg** [comment]
Exactly. I'll put this as an issue!

**Comment by MansMeg** [comment]
Now thi issue is fixed. Github tests are only run if a GITHUB_PAT is supplied.

**Comment by eerolinna** [comment]
Does CI have GITHUB_PAT?

**Comment by MansMeg** [comment]
Yes. Its a secure env variable for github access.

**Comment by eerolinna** [comment]
From what I understand PRs from other repos won't be able to use it (for security reasons, see https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings for more). I guess that is acceptable, we just have to keep it in mind.

Alternatively we could have a small sanity test for the remote pdb that gets run when GITHUB_PAT is not supplied. Something like getting model code and dataset for 8 schools posterior, that probably wouldn't cause too many API calls.

**Comment by MansMeg** [comment]
That could be reasonable. I'll add that as an issue. Each IP address has 60 calls per hour without a PR. But, for example, you can just add your PAT to your Travis and it will run the tests. I think the only problem is when people are doing PRs.

**Pull request merged**
