### PR TITLE
Deleted _MACOSX folders from kidiq.json.zip and kidiq_with_mom_work.j…

### PR DESCRIPTION
**Pull request by jarnefeltoliver**
…son.zip and modified the python README.md

### CODE REVIEW

**Comment by eerolinna** [comment]
Hey, regarding the python readme modifications, as far as I understand using `setup.py` directly is not recommended. Using `pip install .` or `python -m pip install .` would be better.

**Comment by eerolinna** [comment]
Can you change the readme to use one of these?

**Comment by jarnefeltoliver** [comment]
Done. Now reads:
from main directory run `pip install .`

**Comment by eerolinna** [comment]
Thanks!

**Pull request merged**
