### PR TITLE
Fix R tests in .travis.yml

### PR DESCRIPTION
**Pull request by eerolinna**
I think this should do the job, let's see what CI says.

### CODE REVIEW

**Comment by MansMeg** [comment]
Did not seem to work?

**Comment by eerolinna** [comment]
R runs now but there's an error with finding `GLIBCXX_3.4.20`. More details at https://travis-ci.org/MansMeg/posteriordb/jobs/574857500

Any idea what could be causing this?

**Comment by eerolinna** [comment]
I'm trying some things now. I'll be adding commits here but I want to rewrite the commit history once travis is working again, so wait with merging till that is done.

**Comment by eerolinna** [comment]
Well now it works. I followed the workaround from here https://github.com/yihui/travis-blogdown/issues/1 (except I used bionic instead of xenial, so ubuntu 18.04 instead of 16.04). I'll try removing the redundant top-level R config now.

**Comment by eerolinna** [comment]
Do you know by the way if there's anything to make R builds faster? Python takes 1 min while R takes 2.5 min. It looks like R is installed from scratch every time, I wonder if there's a way to cache that.

**Comment by MansMeg** [comment]
R is cached. I think it takes slightly longer + I have tests that take some seconds.

**Comment by eerolinna** [comment]
Let's try with lowercase `r` and no `dist`.

**Comment by eerolinna** [comment]
Works, this is ready for merge.

**Comment by MansMeg** [comment]
Nice!

**Comment by eerolinna** [comment]
The build was also faster, looks like caching needed the lowercase `r`.

**Comment by eerolinna** [comment]
Also if you add r: devel back at some point I think this won't work
```yml
matrix:
  include:
    - language:
        - release
        - devel
      r: release
      cache: packages
      warnings_are_errors: true
      before_install: cd rpackage
```
but this will
```yml
matrix:
  include:
    - language: r
      r: release
      cache: packages
      warnings_are_errors: true
      before_install: cd rpackage
    - language: r
      r: devel
      cache: packages
      warnings_are_errors: true
      before_install: cd rpackage
```
I'm not 100% sure though.

**Comment by MansMeg** [comment]
Yes. Travis did not got what to do when language was wrong.

**Comment by MansMeg** [comment]
Yes. Thats right.

**Pull request merged**
